// #import "Basic";

Person :: struct {
    name: string;
    age: int;


    Person2 :: struct {
        name: string;
        age: int;
    }

    is_this_ok := false;
}

TOKEN :: 20;

// TOKEN :: "x60992xllop";
// ESCAPED_STRING :: ">>> 20202 Some string inside string \"haha!\";";
// RESTRICTED_AGE :: 18;
// PI :: 3.14159265359;
// // Komentář

//     Více 
//     řádkový
//     Komentář


// Gender :: enum {
//     Male;
//     Woman;
//     Other;
// }

jej := "d";

parse :: (file: string, line: int, column: int) {
    
}

main :: () {

}